apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: label-master-mcp
  namespace: gitops-operations
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - oc label machineconfigpool master custom-kubelet=large-pods
        env:
        - name: HOME
          value: /tmp/cli-patch
        image: registry.redhat.io/openshift4/ose-cli:v4.12
        name: patch-cli
      restartPolicy: Never
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa