apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: wait-for-master-mcp
  namespace: gitops-operations
spec:
  backoffLimit: 10
  completions: 2
  template:
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |-
          sleep 40
          for pool in $MCP
          do
            echo "Waiting for $pool MCP to update "
            echo ""
            until oc wait --for condition=updated --timeout=60s mcp $pool
            do
              echo "...still waiting for $pool to update "
              echo ""
            done
          done
          echo "DONE"
        env:
        - name: HOME
          value: /tmp/mcp
        - name: MCP
          value: master
        image: registry.redhat.io/openshift4/ose-cli:v4.12
        name: mcp-wait-job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30