apiVersion: batch/v1
kind: Job
metadata:
  namespace: gitops-operations
  name: patch-job-template
spec:
  template:
    spec:
      containers:
      - name: patch-cli
        image: registry.redhat.io/openshift4/ose-cli:v4.12
        command: 
          - /bin/bash
          - -c
          - To Be Patched
        env:
        - name: HOME
          value: '/tmp/cli-patch'
      restartPolicy: Never
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
  backoffLimit: 2