apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-config
  annotations:
    argocd.argoproj.io/sync-wave: '0' 
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: kubelet-config
    repoURL: 'https://github.com/waljaber/mco-gitops.git'
    targetRevision: HEAD
  project: cluster-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
