apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../templates/job-template
- ../templates/machine-config

patches:
- path: pause-mcp.yaml
  target:
    group: batch
    version: v1
    kind: Job
    name: patch-job-template

- path: resume-mcp.yaml
  target:
    group: batch
    version: v1
    kind: Job
    name: patch-job-template

- path: master-ntp-mc-config.yaml
  target:
    group: machineconfiguration.openshift.io
    version: v1
    kind: MachineConfig
    name: mc-template